[features]
seeds = true
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[workspace]
members = [
    "programs/kernel",
    "programs/services/session_builder",
]

[programs.localnet]
valence-kernel = "11111111111111111111111111111112"
session_builder = "11111111111111111111111111111114"

[programs.testnet]
valence-kernel = "11111111111111111111111111111112"
session_builder = "11111111111111111111111111111114"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/hxrts/keypair.json"

[scripts]
test = "cargo test --workspace" 