[workspace]
members = ["programs/*"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
valence_kernel = "Va1ence111111111111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"