[workspace]
members = [
    # New clean architecture programs
    "programs/gateway",      # Entry point router singleton
    "programs/registry",     # Function registry singleton
    "programs/verifier",     # Verification routing singleton
    "programs/shard",        # User shard template
    
    # Off-chain components (built with regular cargo)
    "sdk",                   # SDK moved to root level
    "services/lifecycle_manager", # Lifecycle manager service
    # "tests",               # Temporarily excluded until new programs are ready
]
# Exclude old implementation and e2e tests (they have their own workspace)
exclude = ["programs_old", "tests/e2e", "artifacts"]
resolver = "2"

# Exclude on-chain programs from workspace builds to avoid conflicts
# Use scripts/build-onchain.sh to build these
default-members = [
    "sdk",                   # SDK at root level
    "services/lifecycle_manager", # Lifecycle manager service
    # "tests",               # Temporarily excluded until new programs are ready
]

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
borsh = "0.10.3"
sha2 = "0.10.8"
bytemuck = "1.14.0"
spl-token = { version = "6.0", features = ["no-entrypoint"] }
spl-associated-token-account = "6.0"
bs58 = "0.5.1"
base64 = "0.22.1"
# solana-program = "2.0" # Use anchor-lang's re-export instead
solana-sdk = "2.0"
solana-client = "2.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0.75"
rand = "0.8.5"
num-bigint = "0.4.4"
num-traits = "0.2.17"
thiserror = "1.0.50"
uuid = { version = "1.0", default-features = false, features = ["serde"] }
# Pin dependencies to avoid edition 2024 requirement
base64ct = "1.6.0"
spki = "=0.7.2"  # Last version before requiring newer base64ct
pkcs8 = "=0.10.2"
ecdsa = "=0.16.8"
ed25519-dalek = "=2.0.0"  # Version 2.1.x may pull newer deps

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(test)'] }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# Allow some pedantic lints that are too strict
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_possible_wrap = "allow"






