[workspace]
resolver = "2"
members = [
    "programs/valence-core",
    "programs/valence-extensions",
]
exclude = [
    "bloom",
]

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-client = "0.31.1"
solana-program = "2.1.6"
solana-sdk = "2.1.6"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1