[workspace]
resolver = "2"
members = [
    "programs/authorization",
    "programs/registry", 
    "programs/processor",
    "programs/base_account",
    "programs/storage_account",
    "programs/zk_verifier",
    "test-helpers",
    "tests",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

# [profile.dev.package.litesvm]
# opt-level = 3

# We're using consistent versions in each Cargo.toml directly instead of patching
# Patching was causing "patch points to the same source" errors
# [patch.crates-io]
# solana-program = { version = "1.18.26" }
# solana-sdk = { version = "1.18.26" }
# spl-token = { version = "4.0.3" }
# spl-token-2022 = { version = "1.0.0" }
# spl-memo = { version = "4.0.4" }
# spl-associated-token-account = { version = "2.3.0" }
