[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "ERdxmzFtjsA29ceTC6MF9qtfDA1qLV2S3krStCCbbJbF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 