[package]
name = "session_builder"
version = "0.1.0"
description = "Off-chain session building service for Valence Protocol"
edition = "2021"
authors = ["Valence Protocol"]
license = "MIT"

[[bin]]
name = "session_builder"
path = "src/main.rs"

[dependencies]
# Core dependencies
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Solana dependencies
solana-client = "2.0"
solana-sdk = "2.0"
# solana-program = "2.0" # Use anchor-lang's re-export instead
anchor-lang = "0.31.1"

# Valence domain client for Solana interaction (off-chain only)
# NOTE: coprocessor feature disabled for compatibility with nix environment (Rust 1.84)
# To build with coprocessor support, use system cargo with Rust 1.85+
valence-domain-clients = { path = "../../../submodules/valence-domain-clients", features = ["solana"] }

# Configuration and environment
clap = { version = "4.4", features = ["derive"] }
dotenvy = "0.15"

# Async and concurrency
futures = "0.3"
async-trait = "0.1"

# Monitoring and metrics
prometheus = "0.13"
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }

# Crypto and serialization
bs58 = "0.5"
borsh = "0.10"

# Error handling and retries
backoff = "0.4"

# Utilities
uuid = { version = "1.6", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"

[dev-dependencies]
tempfile = "3.8"
mockall = "0.12"

 