[package]
name = "token_transfer"
version = "0.1.0"
description = "Valence Protocol Token Transfer Library"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = { version = "0.29.0", features = ["token", "token_2022"] }
solana-program = "1.18.26"
base_account = { path = "../../base_account", features = ["cpi"] }
storage_account = { path = "../../storage_account", features = ["cpi"] }
borsh = "0.10.0"
thiserror = "1.0.56"
spl-token = { version = "4.0.3", features = ["no-entrypoint"] }
spl-token-2022 = { version = "1.0.0", features = ["no-entrypoint"] }
spl-memo = { version = "4.0.4", features = ["no-entrypoint"] }

[dev-dependencies]
solana-sdk = "1.18.26"
litesvm = "0.3" 