[package]
name = "token_transfer"
version = "0.1.0"
description = "Valence Protocol Token Transfer Library"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = { version = "0.28.0", features = ["token"] }
solana-program = "~1.16.0"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.1.3", features = ["no-entrypoint"] }
base_account = { path = "../../base_account", features = ["cpi"] }
storage_account = { path = "../../storage_account", features = ["cpi"] }
borsh = "0.10.0" 