[package]
name = "valence-utils"
version = "0.1.0"
edition = "2021"
description = "Utility functions for Valence Solana programs"

[dependencies]
anchor-lang = "0.31.1"
solana-program = "2.1.0"
borsh = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] } 