name: Quick Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: timewave
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Quick checks
        run: |
          # Check flake
          nix flake check -L --no-update-lock-file
          
          # Run fast checks in Nix environment
          nix develop -L --no-update-lock-file -c bash -c "
            echo '=== Format check ==='
            cargo fmt --all -- --check
            
            echo '=== Quick clippy check (no deps) ==='
            cargo clippy --no-deps -- -D warnings
            
            echo '=== Check compilation ==='
            cargo check --workspace
          "